# Generated by Django 3.0.3 on 2021-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=500)),
                ('rating', models.IntegerField(choices=[(1, '1-Very Bad'), (2, '2-Bad'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Excellent')])),
            ],
        ),
    ]
