# Generated by Django 3.0.3 on 2021-04-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
